# This is the configuration used to check the rubocop source code.
# See details for the settings below here: http://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop

# to create the todo file, run this in root directory: rubocop --auto-gen-config
# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'config/**/*'
  TargetRubyVersion: 2.3.3

# ================================
# Lint
# ================================

Lint/UnusedBlockArgument:
  Exclude:
    - 'config/unicorn.rb'  

# ================================
# Rails
# ================================

Rails/DynamicFindBy:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/Output:
  Exclude:
    - 'app/controllers/application_controller.rb'

# ================================
# Metrics
# ================================

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# ================================
# Style
# ================================

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: false

# ================================
# Rails
# ================================
